In [1]:
import numpy as np
import pandas as pd

In [3]:
vals = [
    [1, 2],
    [3.3, 4.4],
    [0.2, 88],
]
a = np.array(vals)
df = pd.DataFrame(a)
df.index.name = 'observations'
df.columns = pd.MultiIndex.from_product([['x', 'y']], names=['vars'])
display(a)
display(df)
display(df.describe())
df.values

array([[ 1. ,  2. ],
       [ 3.3,  4.4],
       [ 0.2, 88. ]])

vars            x     y
observations           
0             1.0   2.0
1             3.3   4.4
2             0.2  88.0

vars          x          y
count  3.000000   3.000000
mean   1.500000  31.466667
std    1.609348  48.974007
min    0.200000   2.000000
25%    0.600000   3.200000
50%    1.000000   4.400000
75%    2.150000  46.200000
max    3.300000  88.000000

array([[ 1. ,  2. ],
       [ 3.3,  4.4],
       [ 0.2, 88. ]])

In [44]:
display(np.cov(a))
display(np.cov(a, rowvar=False))
df.cov()

array([[5.00000e-01, 5.50000e-01, 4.39000e+01],
       [5.50000e-01, 6.05000e-01, 4.82900e+01],
       [4.39000e+01, 4.82900e+01, 3.85442e+03]])

array([[   2.59      ,  -53.74      ],
       [ -53.74      , 2398.45333333]])

vars      0            1
vars                    
0      2.59   -53.740000
1    -53.74  2398.453333

In [42]:
df.columns

MultiIndex([(0,),
            (1,)],
           names=['vars'])