## Matrix multiplication by vector

$\boldsymbol{W}$ - $M \times m1$ ($h \times w$) matrix; $M$ - height; $m1$ - width

$\boldsymbol{W}=\{w_{kj}; k=1, 2, ..., M; j=1, 2, ..., m1\}={\begin{bmatrix}w_{1,1}&w_{1,2}&...&w_{1,m1}\\...&...&...&...\\w_{k,1}&w_{k,2}&...&w_{M,m1}\end{bmatrix}}$

$\boldsymbol{x}={\begin{bmatrix}x_1&...&x_{m1}\end{bmatrix}}^T={\begin{bmatrix}x_1\\...\\x_{m1}\end{bmatrix}}$

$\boldsymbol{y}=\boldsymbol{W}\boldsymbol{x}={\begin{bmatrix}y_1\\...\\y_{m1}\end{bmatrix}}$

${\begin{bmatrix}0&1&2&3\\4&5&6&7\\8&9&10&11\end{bmatrix}}{\begin{bmatrix}1\\10\\100\\1000\end{bmatrix}}={\begin{bmatrix}3210\\7654\\12098\end{bmatrix}}$

[np.matmul (@ operator) documentation](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)


In [71]:
import numpy as np

M, m1 = 3, 4
W = np.arange(M*m1).reshape(M, m1)
x = np.array([1, 10, 100, 1000])
y = np.matmul(W, x)
W, x, y

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([   1,   10,  100, 1000]),
 array([ 3210,  7654, 12098]))

In [69]:
W @ x

array([ 3210,  7654, 12098])

In [72]:
x_ = x.reshape(-1, 1)
y_ = np.matmul(W, x_) 
W, x_, y_, W @ x_

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[   1],
        [  10],
        [ 100],
        [1000]]),
 array([[ 3210],
        [ 7654],
        [12098]]),
 array([[ 3210],
        [ 7654],
        [12098]]))


[np.dot documentation](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)

In [65]:
# If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.
# If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.
np.dot(W, x), np.dot(W, x_)

(array([ 3210,  7654, 12098]),
 array([[ 3210],
        [ 7654],
        [12098]]))

In [66]:
len_sq = np.dot(x,x)
# If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).
len_sq, len_sq ** 0.5, np.sqrt(len_sq)

(1010101, 1005.037810234023, 1005.037810234023)

In [73]:
# If a is an N-D array and b is an M-D array (where M>=2), 
# it is a sum product over the last axis of a and the second-to-last axis of b:
# dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

- обратная матрица
- псевдообратная матрица
- ранг
- сингулярность